// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jQiOPOOOOOO'#C`'#C`OOOO'#C_'#C_OpOPO'#C^OQOPO'#CaOOOO'#Cb'#CbQuOPOOQuOPOOOOOO,58x,58xOzOPO,58{OOOO-E6`-E6`OOOO1G.g1G.g",
  stateData: "!P~OWQOXQOYQOZQO[PO]PO^PO~O_SO~PQO_WO~O_SO~O_ZO~O",
  goto: "qVPPWZaejRVOQRORXSTQOSVTOUVSUOVRYU",
  nodeNames: "⚠ Program FirstStatement Verbose Param Statement",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "'o~RXYZnpqn!c!ds!e!f!n!g!h$R!i!j%t!r!s&i!s!t'^~~n~sO_~~vP#g#hy~|P#g#h!P~!SP#i#j!V~!YP#a#b!]~!`P#X#Y!c~!fP![!]!i~!nO]~~!qP#c#d!t~!wP#b#c!z~!}P#V#W#Q~#TP#`#a#W~#ZP#i#j#^~#aP#g#h#d~#gP#]#^#j~#mP#c#d#p~#sP#b#c#v~#yP![!]#|~$RO^~~$UP#l#m$X~$[Q#T#U$b#X#Y%P~$eP#a#b$h~$kP#d#e$n~$qP#`#a$t~$wP#X#Y$z~%POW~~%SP#f#g%V~%YP#V#W%]~%`P#]#^%c~%fP#g#h%i~%lP#X#Y%o~%tOX~~%wP#]#^%z~%}P#j#k&Q~&TP#X#Y&W~&ZP#b#c&^~&aP![!]&d~&iO[~~&lP#f#g&o~&rP#c#d&u~&xP#c#d&{~'OP#Y#Z'R~'UP![!]'X~'^OY~~'aP!g!h'd~'gP!f!g'j~'oOZ~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
